Fixed template hooks

diff --git a/templates/crates/unison/hooks/post_create b/templates/crates/unison/hooks/post_create
--- a/templates/crates/unison/hooks/post_create
+++ b/templates/crates/unison/hooks/post_create
@@ -7,30 +7,24 @@ set -e
 
 # Get crate configuration from user input
 crateName=${CRATE_NAME}
-crateDescription=$(gum input --prompt "> Crate description -> " --cursor.mode "blink" --value "")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
-crateProtocol=$(gum input --prompt "> Protocol (default: ssh) -> " --cursor.mode "blink" --value "ssh")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
-crateHost=$(gum input --prompt "> Host -> " --cursor.mode "blink" --value "")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
+crateDescription=$(gum input --prompt "> Crate description -> " --cursor.mode "blink" --value "") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
+
+crateProtocol=$(gum input --prompt "> Protocol (default: ssh) -> " --cursor.mode "blink" --value "ssh") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
+
+crateHost=$(gum input --prompt "> Host -> " --cursor.mode "blink" --value "") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
 
 # Verify if crate will use the SSH protocol
 if [ "${crateProtocol}" = "ssh" ]; then
 	crateSSHEnabled=true
-	crateSSHKeyPath=$(gum input --prompt "> SSH key path -> " --cursor.mode "blink" --value "${HOME}/.ssh/")
-	if [ $? -ne 0 ]; then
-		${SYNCTROPY_UTILS} error "Failed to get user input"
-		exit 1
-	fi
+	crateSSHKeyPath=$(gum input --prompt "> SSH key path -> " --cursor.mode "blink" --value "${HOME}/.ssh/") || \
+		(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+		exit 1)
 else
 	crateSSHEnabled=false
 	crateSSHKeyPath=""
@@ -79,10 +73,8 @@ jsonContent=$(jq -n \
 }')
 
 # Write content to configuration file
-echo "${jsonContent}" > ${CRATE_DIR}/config.json
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to write to configuration file"
-	exit 1
-fi
+echo "${jsonContent}" > ${CRATE_DIR}/config.json || \
+	(${SYNCTROPY_UTILS} error "Failed to write to configuration file" && \
+	exit 1)
 
 exit 0
diff --git a/templates/crates/unison/hooks/pre_transaction b/templates/crates/unison/hooks/pre_transaction
--- a/templates/crates/unison/hooks/pre_transaction
+++ b/templates/crates/unison/hooks/pre_transaction
@@ -6,11 +6,9 @@ set -e
 #
 
 is_ssh_enabled() {
-	sshEnabled=$(cat ${CRATE_DIR}/config.json | jq -r '.ssh.enabled')
-	if ! [ $? = 0 ]; then
-		${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file."
-		exit 1
-	fi
+	sshEnabled=$(cat ${CRATE_DIR}/config.json | jq -r '.ssh.enabled') || \
+		(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
+		exit 1)
 
 	if [ "${sshEnabled}" = "true" ]; then
 		return 0
@@ -28,17 +26,13 @@ is_ssh_enabled() {
 #
 
 if is_ssh_enabled; then
-	SSH_KEY_PATH=$(cat "${CRATE_DIR}/config.json" | jq -r '.ssh.keyPath')
-	if ! [ $? = 0 ]; then
-		${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file"
-		exit 1
-	fi
+	SSH_KEY_PATH=$(cat "${CRATE_DIR}/config.json" | jq -r '.ssh.keyPath') || \
+		(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file" && \
+		exit 1)
 
-	${SYNCTROPY_UTILS} sshagent-start "${SSH_KEY_PATH}" ${CRATE_TEMP_DIR}
-	if ! [ $? = 0 ]; then
-		${SYNCTROPY_UTILS} error "Failed to start SSH agent"
-		exit 1
-	fi
+	${SYNCTROPY_UTILS} sshagent-start "${SSH_KEY_PATH}" ${CRATE_TEMP_DIR} || \
+		(${SYNCTROPY_UTILS} error "Failed to start SSH agent" && \
+		exit 1)
 else
 	${SYNCTROPY_UTILS} attention "SSH is disabled in crate configuration"
 fi
diff --git a/templates/targets/unison/hooks/post_create b/templates/targets/unison/hooks/post_create
--- a/templates/targets/unison/hooks/post_create
+++ b/templates/targets/unison/hooks/post_create
@@ -6,44 +6,35 @@ set -e
 #
 
 # Get crate configuration
-crateName=$(cat ${CRATE_DIR}/config.json | jq -r '.name')
-if ! [ $? = 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file."
-	exit 1
-fi
-crateDescription=$(cat ${CRATE_DIR}/config.json | jq -r '.description')
-if ! [ $? = 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file."
-	exit 1
-fi
-crateProtocol=$(cat ${CRATE_DIR}/config.json | jq -r '.protocol')
-if ! [ $? = 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file."
-	exit 1
-fi
-crateHost=$(cat ${CRATE_DIR}/config.json | jq -r '.host')
-if ! [ $? = 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file."
-	exit 1
-fi
+crateName=$(cat ${CRATE_DIR}/config.json | jq -r '.name') || \
+	(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
+	exit 1)
+
+crateDescription=$(cat ${CRATE_DIR}/config.json | jq -r '.description') || \
+	(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
+	exit 1)
+
+crateProtocol=$(cat ${CRATE_DIR}/config.json | jq -r '.protocol') || \
+	(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
+	exit 1)
+
+crateHost=$(cat ${CRATE_DIR}/config.json | jq -r '.host') || \
+	(${SYNCTROPY_UTILS} error "Failed to read/parse crate configuration file." && \
+	exit 1)
 
 # Get target configuration from user input
 targetName=${TARGET_NAME}
-targetDescription=$(gum input --prompt "> Target description -> " --cursor.mode "blink" --value "")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
-targetPrimaryDirectory=$(gum input --prompt "> Primary directory (e.g., local) -> " --cursor.mode "blink" --value "")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
-targetSecondaryDirectory=$(gum input --prompt "> Secondary directory (e.g., remote) -> " --cursor.mode "blink" --value "")
-if [ $? -ne 0 ]; then
-	${SYNCTROPY_UTILS} error "Failed to get user input"
-	exit 1
-fi
+targetDescription=$(gum input --prompt "> Target description -> " --cursor.mode "blink" --value "") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
+
+targetPrimaryDirectory=$(gum input --prompt "> Primary directory (e.g., local) -> " --cursor.mode "blink" --value "") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
+
+targetSecondaryDirectory=$(gum input --prompt "> Secondary directory (e.g., remote) -> " --cursor.mode "blink" --value "") || \
+	(${SYNCTROPY_UTILS} error "Failed to get user input" && \
+	exit 1)
 
 # Display configuration and ask for user confirmation
 echo ""
